#!/usr/bin/env bash
# Generate a source-referenced platform API inventory.
# Usage: DX_COMMON_GO=/path/to/dx-common-go bash scripts/gen-api.sh
set -euo pipefail

cd "$(dirname "$0")/.."

lib_dir="../dx-common-go"
if printenv DX_COMMON_GO >/dev/null 2>&1; then
  lib_dir="$(printenv DX_COMMON_GO)"
fi
if [[ ! -d "$lib_dir/platform" ]]; then
  echo "dx-common-go checkout not found at $lib_dir" >&2
  echo "Set DX_COMMON_GO to the library checkout." >&2
  exit 1
fi

output_file="docs/reference/generated-api.md"
api_tmp="$(mktemp)"
trap 'rm -f "$api_tmp"' EXIT

source_ref="$(git -C "$lib_dir" rev-parse --short=12 HEAD)"
source_date="$(git -C "$lib_dir" show -s --format=%cs HEAD)"
module_path="$(awk '$1 == "module" {print $2; exit}' "$lib_dir/go.mod")"

{
  echo "---"
  echo "title: Generated API Inventory"
  echo "description: Generated exported declaration inventory for the platform packages."
  echo "---"
  echo
  echo "# Generated API inventory"
  echo
  echo "> Generated from \`$module_path\` at commit \`$source_ref\`"
  echo "> (source commit date: $source_date). Do not edit this file by hand."
  echo

  while IFS= read -r package_path; do
    [[ -n "$package_path" ]] || continue
    relative="$(printf '%s' "$package_path" | sed "s#^$module_path/##")"
    echo "## \`$relative\`"
    echo
    echo '~~~go'
    (cd "$lib_dir" && go doc -short "./$relative" 2>/dev/null)
    echo '~~~'
    echo
  done < <(
    find "$lib_dir/platform" -type f -name '*.go' ! -name '*_test.go' -print |
      sed 's#/[^/]*$##' |
      LC_ALL=C sort -u |
      sed "s#^$lib_dir/#$module_path/#"
  )
} > "$api_tmp"

mv "$api_tmp" "$output_file"
trap - EXIT
echo "generated $output_file from $source_ref"
